spec.containers.envFrom.secretRef
spec.initContainers.envFrom.secretRef
spec.volumes.cephfs.secretRef
spec.volumes.cinder.secretRef
spec.volumes.csi.nodePublishSecretRef
spec.volumes.flexVolume.secretRef
spec.volumes.iscsi.secretRef
spec.volumes.rbd.secretRef
spec.volumes.scaleIO.secretRef
spec.volumes.storageos.secretRef
